# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(270, 80, 160, 31))
        self.name_label.setObjectName("name_label")
        self.pin_label = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pin_label.setGeometry(QtCore.QRect(270, 210, 160, 31))
        self.pin_label.setObjectName("pin_label")
        self.deposit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deposit_button.setGeometry(QtCore.QRect(80, 110, 100, 32))
        self.deposit_button.setObjectName("deposit_button")
        self.withdraw_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.withdraw_button.setGeometry(QtCore.QRect(200, 110, 100, 32))
        self.withdraw_button.setObjectName("withdraw_button")
        self.balance_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.balance_button.setGeometry(QtCore.QRect(320, 110, 100, 32))
        self.balance_button.setObjectName("balance_button")
        self.balance_display = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.balance_display.setGeometry(QtCore.QRect(125, 180, 250, 150))
        self.balance_display.setObjectName("balance_display")
        self.amount_label = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.amount_label.setGeometry(QtCore.QRect(150, 50, 200, 31))
        self.amount_label.setObjectName("amount_label")
        self.name_title = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.name_title.setGeometry(QtCore.QRect(70, 70, 150, 50))
        self.name_title.setObjectName("name_title")
        self.pin_title = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.pin_title.setGeometry(QtCore.QRect(70, 200, 150, 50))
        self.pin_title.setObjectName("pin_title")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(80, 300, 150, 50))
        self.login_button.setObjectName("login_button")
        self.create_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_button.setGeometry(QtCore.QRect(270, 300, 150, 50))
        self.create_button.setObjectName("create_button")
        self.create_button.raise_()
        self.login_button.raise_()
        self.pin_title.raise_()
        self.name_title.raise_()
        self.name_label.raise_()
        self.pin_label.raise_()
        self.deposit_button.raise_()
        self.withdraw_button.raise_()
        self.balance_button.raise_()
        self.balance_display.raise_()
        self.amount_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.deposit_button.setText(_translate("MainWindow", "Deposit"))
        self.withdraw_button.setText(_translate("MainWindow", "Withdraw"))
        self.balance_button.setText(_translate("MainWindow", "Balance"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.create_button.setText(_translate("MainWindow", "Create Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
